import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import Nav from '../components/nav/Nav'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Immeuble à Raismes'
  // description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className='flex flex-col items-center justify-center min-h-screen p-6 bg-gray-100'>
          <div className='max-w-4xl bg-white p-8 rounded-lg shadow-lg'>
            <Nav />
            <div className='p-4'>{children}</div>
          </div>
        </main>
      </body>
    </html>
  )
}
