import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import Link from 'next/link'
import { ReactNode } from 'react'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Immeuble à Raismes'
  // description: 'Generated by create next app'
}

const Layout = ({ children }: { children: ReactNode }) => (
  <div>
    <nav className='bg-gray-800 p-4'>
      <ul className='flex space-x-4 text-white'>
        <li>
          <Link className='text-white' href='/'>
            Accueil
          </Link>
        </li>
        <li>
          <Link href='/lot1'>Local commercial</Link>
        </li>
        <li>
          <Link href='/lot2'>T3</Link>
        </li>
        <li>
          <Link href='/lot3'>premier T2</Link>
        </li>
        <li>
          <Link href='/lot4'>deuxième T2</Link>
        </li>
        <li>
          <Link href='/lot5'>troisième T2</Link>
        </li>
        <li>
          <Link href='/lot6'>Studio</Link>
        </li>
        <li>
          <Link href='/garages'>Garages</Link>
        </li>
        <li>
          <Link href='/commun'>Parties communes</Link>
        </li>
        <li>
          <Link href='/contact'>Contact</Link>
        </li>
      </ul>
    </nav>
    <div className='p-4'>{children}</div>
  </div>
)

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className='flex flex-col items-center justify-center min-h-screen p-6 bg-gray-100'>
          <div className='max-w-4xl bg-white p-8 rounded-lg shadow-lg'>
            <Layout>{children}</Layout>
          </div>
        </main>
      </body>
    </html>
  )
}
